# This file defines the content types on the website. See the documentation for
# details: https://docs.bolt.cm/contenttypes/intro

# The Homepage content type is a singleton: There can be only one record of this
# content type.

homepage:
    name: Homepage
    singular_name: Homepage
    fields:
        title:
            type: text
            class: large
            group: content
            localize: true
            label: Title
            postfix: |
                The 'Homepage' can contain basic information about the website. This title will be
                shown on the homepage of the website, as the name implies. To change the
                <em><strong>name</strong></em> of the site, as is shown in the header, and the tab
                in the webbrowser, edit <code>sitename:</code> in the configuration file.
        banner_image:
            type: image
        introduction:
            type: redactor
            localize: true
        content:
            type: redactor
            localize: true
        contentlink:
            type: text
            label: Link
            placeholder: 'contentType/slug or https://example.org/'
            postfix: "Use this to add a link for this Homepage. This could either be an 'internal' link like <tt>page//about</tt>, if you use a contentType/slug combination. Otherwise use a proper URL, like `https://example.org`."
            fixture_format: '{url}'
        titre_produit:
            type: text
            group: "Produits"
        description_produit:
            type: redactor
        thumbs_images:
            type: collection
            limit: 3
            fields:
                image:
                    type: image
                    
        agricfarm_title:
            type: text
            group: "Agric Farm section"
            label: "Titre du section d'agric"
        agricfarm_desc:
            type: redactor
        about_left_image:
            type: image
        about_right_image:
            type: image
        fruits_title:
            type: text
            group: "Produit"
        fruits_desc:
            type: text
        product_sec_image:
            type: image
        slug:
            type: slug
            uses: title
            group: Meta 
        seo:
            type: seo
            group: "SEO settings"
    viewless: false
    taxonomy: [ categories, tags, foobars ]
    locales: ['en', 'nl', 'pt_BR', 'es']
    singleton: true
    icon_many: "fa:home"
    icon_one: "fa:home"


# Pages can be used for the more 'static' pages on your site. This content-type
# has a 'templateselect' field, which allows you to override the record_template
# setting for an individual page.
# The taxonomy for this ContentType is defined as 'groups', which is a so-called
# "grouping taxonomy". This way you can easily group sets of pages that logically
# belong together. If your site has a 'services' section, in which you'd like to
# list the different types of services a company provides, you can group these
# together.

pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large
            group: content
        teaser:
            type: textarea
            postfix: |
                A text-only version of the content, that can be used to "tease"
                the content when it's used in listing pages or search results.
        image:
            type: image
            label: Highlighted image
        body:
            type: redactor
            height: 300px
        slug:
            type: slug
            uses: title
            group: Meta
        template:
            type: templateselect
            filter: '/^[^_].*\.twig$/'
    taxonomy: [ groups ]
    records_per_page: 5
    order: id

# Agricultural products
agricproducts:
    name: AgricProducts
    singular_name: AgricProduct
    viewless: true
    fields:
        title: 
            type: text
        description:
            type: text
        image:
            type: image
        slug:
            type: slug

# Service 
Services:
    name: Services
    singular_name: Service
    fields:
        title: 
            type: text
        content:
            type: redactor
        image:
            type: image
            
# About page
Apropos:
    name: Apropos
    singular_name: Apropos
    singleton: true
    fields:
        title: 
            type: text
        content:
            type: redactor
        main_image:
            type: image
        history:
            type: text
            placeholder: "Titre de l'historique"
            group: "Historique"
        history_image:
            type: image
        history_desc:
            type: redactor
    record_template: apropos.twig
    
            
        
